### ISSUE TITLE
Improve sponsors page

### ISSUE THREAD

**Issue by rithiksachdev** [rithiksachdev/ecellweb#15]

**Comment by Git-Harshit** [comment]
@rithiksachdev Sir, please leave it on me. May I update it with whatever is made as soon as possible?

**Comment by Git-Harshit** [comment]
Ok @rithiksachdev sir! Thank you for acknowledging my work. I will implement these mentioned changes as early as possible.

**Comment by Git-Harshit** [comment]
The sponsors page is basically ready by now. Minor updations to the page can be dealt with later on. Now, this issue is being closed.
