### ISSUE TITLE
Navbar issue: navigation bar, if expanded in mobile or tablet screens, does not re-collapse using toggler. 

### ISSUE THREAD

**Issue by Git-Harshit** [rithiksachdev/ecellweb#17]
The navigation bar, when expanded in small screens, is becoming irresponsive, causing troubles to browse any webpage. It collapses again, only on refreshing the webpage.

**Comment by rithiksachdev** [comment]
It's because you have made incorrect changes.

**Comment by rithiksachdev** [comment]
I've rolled back all your changes. Work on your local repo and push only if you don't create this issue.

**Comment by Git-Harshit** [comment]
Okay sir! I admit my mistake and will ensure that the code runs perfectly on my machine before pushing my commit. Thanks for fixing it!
