### ISSUE TITLE
Create a new preloader for the website

### ISSUE THREAD

**Issue by rithiksachdev** [rithiksachdev/ecellweb#18]
The website is loaded before the animation is finished.

**Comment by Git-Harshit** [comment]
Fixed! 

Please check the latest webpage on pure-..., and if everything is fine, you can close the issue! 😄

**Comment by Git-Harshit** [comment]
Thanks for assigning it to me! I will try my best to make it more better!

**Comment by rithiksachdev** [comment]
Great Work! The loader looks good. I will close this issue.
