### ISSUE TITLE
Minor contact form fixes 

### ISSUE THREAD

**Issue by divyanshsood00** [rithiksachdev/ecellweb#20]
Placeholders are being added in form and also that fields except contact number is being made required(essential).....actually i happened to notice the wrong spelling in address(adress was written)...
corrected that and also i was thinking of adding autofocus attribute but it started the homepage from form...so don't try that

**Comment by divyanshsood00** [comment]
Improved the number field and added pattern for number for identification
Again added place holders :)

**Comment by Git-Harshit** [comment]
> Improved the number field and added pattern for number for identification
> Again added place holders :)

@divyanshsood00 Weren't placeholders already added before?

**Comment by rithiksachdev** [comment]
We don't want any place holders. Remove them

**Comment by divyanshsood00** [comment]
okay okay removing them
