### ISSUE TITLE
Create a Campus Ambassador Dashboard (Profile Page)

### ISSUE THREAD

**Issue by rithiksachdev** [rithiksachdev/ecellweb#28]
Workflow - Campus Ambassador link - .../ca/ -> login using facebook -> dashboard -> task and scores for respective students

**Comment by Git-Harshit** [comment]
Nice Idea! I think, at the same time, we can add an option for it in other areas like the navbar or internships page!

**Comment by rithiksachdev** [comment]
No, it can't be added to the navbar. The navbar will only have other important features. I don't want a lot of people to get redirected on that page.

**Comment by Git-Harshit** [comment]
Ok @rithiksachdev sir! You're correct! We can definitely look about this options-providing later.

**Comment by Git-Harshit** [comment]
Thanks @rithiksachdev sir for assigning it to me.
