### ISSUE TITLE
Add animation on scroll using wow.js and animate.css 

### ISSUE THREAD

**Issue by rithiksachdev** [rithiksachdev/ecellweb#29]

**Comment by Git-Harshit** [comment]
Thank you for assigning me this issue, @rithiksachdev sir! I will try to implement it successfully at earliest!

**Comment by rithiksachdev** [comment]
@Git-Harshit, add an animation to the contact form.

**Comment by Git-Harshit** [comment]
Sure @rithiksachdev sir! It will be done!
