### ISSUE TITLE
Remove the empty slide in owl-carousel

### ISSUE THREAD

**Issue by rithiksachdev** [rithiksachdev/ecellweb#30]
This could be fixed by just upgrading to the latest version of the owl-carousel. You can find more descriptions on how to fix in these links - [StackOverflow](https://stackoverflow.com/questions/39577855/empty-item-in-owl-carousel), [github](https://github.com/laurenchen0631/react-owl-carousel/issues/17)

**Comment by Git-Harshit** [comment]
Good issue, I must mention! I would also like to add that don't you think our owl-carousel at our homepage lacks a title like "Our Testimonials", "Words from our speakers/guests", or any other? Please consider it, and see if any such change could also be implemented for it, possibly just before (above) it.

**Comment by rithiksachdev** [comment]
We could surely add a title to it, the title that you have suggested doesn't fit exactly but we can add it later.
