### ISSUE TITLE
Change the carousel slider 

### ISSUE THREAD

**Issue by rithiksachdev** [rithiksachdev/ecellweb#4]
Add the pictures of people like satyajeet majumdar sir who has visited us and some quote related to that event or his quote.

**Comment by Git-Harshit** [comment]
I will be working on it!

**Comment by rithiksachdev** [comment]
@Git-Harshit use links to pictures and do not store a copy of it in the img folder.

**Comment by Git-Harshit** [comment]
Alright!

**Comment by Git-Harshit** [comment]
Alright!

**Comment by Git-Harshit** [comment]
Yes sir!

**Comment by Git-Harshit** [comment]
The speakers with their original quotations (wherever found) have been set in the same carousel. Please look into the same, and let me know if anything is still remaining for its updation. @rithiksachdev sir, pre-thanks for the same.

**Comment by Git-Harshit** [comment]
Isn't any heading like "Testimonials" or "Words from our speakers" seem to be missing for the carousel? Please let me know if something like that could be added before the carousel.
