### ISSUE TITLE
Team Page is not responsive 

### ISSUE THREAD

**Issue by rithiksachdev** [rithiksachdev/ecellweb#8]
Remove box-shadow using media queries and Social media links are not proper on the phone.

**Comment by rithiksachdev** [comment]
@Dhanu-k make sure you remove the box-shadow using media queries. You can look at rithiksachdev.github.io for reference, you can see the difference when opened in mobile and desktop. Do the same here. Also, make sure you use proper div elements in your cards so that horizontal social media icons don't go vertical and please change the color, font family of your font. The javascript you're using for the text is not necessary here so, you can probably try to ignore it completely. We can use that script as a preloader.

**Comment by rithiksachdev** [comment]
Great work! Let me know if you face any issues.

**Comment by Dhanu-k** [comment]
Sure sir!

**Comment by rithiksachdev** [comment]
Hi @Dhanu-k, It takes a lot of time to load images from drive/LinkedIn URL so, please add the files locally in our img directory. We can close the issue after this final change.
